version: 1
runtime: go
api_version: go1

handlers:
- url: /audio
  static_dir: frontend/static/audio/
  application_readable: true
- url: /js
  static_dir: frontend/static/js_compiled/
  application_readable: true
- url: /css
  static_dir: frontend/static/css_compiled/
  application_readable: true
- url: /images
  static_dir: frontend/static/images/
  application_readable: true
- url: /.*
  script: _go_app


skip_files:
- ^(.*/)?.*\.MF$
- ^(.*/)?.*\.CMF$
- ^(.*/)?.*\.sourcemap$
- ^(.*/)?.*\.map$
- ^(.*/)?.*\node_modules$
